apiVersion: v1
kind: Service
metadata:
  name: {{ template "dgraph.alpha.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "dgraph.name" . }}
    app.kubernetes.io/component: {{ .Values.alpha.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "dgraph.chart" . }}
spec:
  type: {{ .Values.alpha.service.type }}
  ports:
  - port: 8080
    targetPort: 8080
    name: alpha-http
  - port: 9080
    targetPort: 9080
    name: alpha-grpc
  selector:
    app.kubernetes.io/name: {{ include "dgraph.name" . }}
    app.kubernetes.io/component: {{ .Values.alpha.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
