apiVersion: v1
kind: Service
metadata:
  name: {{ template "dgraph.zero.fullname" . }}-headless
  labels:
    app.kubernetes.io/name: {{ include "dgraph.name" . }}
    app.kubernetes.io/component: {{ .Values.zero.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "dgraph.chart" . }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: zero-grpc
    port: 5080
    targetPort: 5080
  selector:
    app.kubernetes.io/name: {{ include "dgraph.name" . }}
    app.kubernetes.io/component: {{ .Values.zero.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
