apiVersion: v1
name: dgraph
version: 1.0.0
appVersion: 1.1.0
description: Dgraph is a horizontally scalable and distributed graph database, providing ACID transactions, consistent replication and linearizable reads.
keywords:
- dgraph
- database
- Graph
- GraphQL
- nosql
home: https://dgraph.io/
sources:
- https://github.com/dgraph-io/dgraph
maintainers:
- name: dgraph
  email: contact@dgraph.io
- name: danielmai
  email: daniel@dgraph.io
- name: david972
  email: david.alexandre@w6d.io
icon: https://dgraph.io/assets/images/logo.png
